#!/usr/bin/env python
# -*- coding: utf-8 -*- #
from __future__ import unicode_literals

import os

AUTHOR = u'IOOS'

SITENAME = u'system-test'
SITESUBTITLE = u'IOOS DMAC System Integration Test project'
SITEURL = ''

# Times and dates.
DEFAULT_DATE_FORMAT = '%b %d, %Y'
TIMEZONE = 'America/New_York'
DEFAULT_LANG = u'en'

# Set the article URL.
ARTICLE_URL = 'blog/{date:%Y}/{date:%m}/{date:%d}/{slug}/'
ARTICLE_SAVE_AS = 'blog/{date:%Y}/{date:%m}/{date:%d}/{slug}/index.html'

# Title menu options.
uri = 'http://ioos.github.io'
MENUITEMS = [('Main', '%s/system-test' % uri),
             ('Archives', '%s/system-test/archives.html' % uri),
             ('About', 'https://github.com/ioos/system-test/wiki'),
             ]
NEWEST_FIRST_ARCHIVES = True

# Github include settings.
GITHUB_USER = 'ioos'
# GITHUB_REPO_COUNT = 0
# GITHUB_SKIP_FORK = True
# GITHUB_SHOW_USER_LINK = True

# Blogroll.
LINKS = (('NOAA', 'http://www.noaa.gov/'),
         ('IOOS', 'http://www.ioos.noaa.gov/'),)

DEFAULT_PAGINATION = 10

# STATIC_OUT_DIR requires pelican 3.3+.
STATIC_PATHS = ['images', 'figures', 'downloads', 'favicon.png']
CODE_DIR = 'downloads/code'
NOTEBOOK_DIR = 'downloads/notebooks'

# Theme and plug-ins.
THEME = 'pelican-octopress-theme'
PLUGIN_PATH = 'pelican-plugins'
PLUGINS = ['summary', 'liquid_tags.img', 'liquid_tags.video',
           'liquid_tags.include_code', 'liquid_tags.notebook',
           'liquid_tags.literal']

DISPLAY_PAGES_ON_MENU = False
DISPLAY_CATEGORIES_ON_MENU = False

# This header file is automatically generated by the notebook plugin.
if not os.path.exists('_nb_header.html'):
    import warnings
    warnings.warn("_nb_header.html not found.  "
                  "Rerun make html to finalize build.")
else:
    EXTRA_HEADER = open('_nb_header.html').read().decode('utf-8')

# Sharing
TWITTER_USER = 'usioosgov'
FACEBOOK_LIKE = True
TWITTER_TWEET_BUTTON = True
TWITTER_LATEST_TWEETS = True
TWITTER_FOLLOW_BUTTON = True
TWITTER_TWEET_COUNT = 3
TWITTER_SHOW_REPLIES = 'false'
TWITTER_SHOW_FOLLOWER_COUNT = 'true'

# RSS/Atom feeds
FEED_ATOM = 'atom.xml'
FEED_DOMAIN = 'http://ioos.github.io/system-test/'
FEED_MAX_ITEMS = 5

# Search
SEARCH_BOX = True

# Ignore HTMLs.
READERS = {'html': None}
